-- Angelique Tarot Supabase schema and RLS baseline.
-- Run this in the Supabase SQL editor before production launch.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    email text not null,
    nickname text default '',
    birthdate date,
    is_premium boolean not null default false,
    stripe_customer_id text,
    stripe_subscription_id text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists stripe_customer_id text;
alter table public.profiles add column if not exists stripe_subscription_id text;
create index if not exists profiles_stripe_customer_id_idx on public.profiles(stripe_customer_id);

create table if not exists public.daily_usage (
    id bigint generated by default as identity primary key,
    user_id text not null,
    usage_date date not null,
    count integer not null default 0,
    shared boolean not null default false,
    ad_bonus integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (user_id, usage_date)
);

create table if not exists public.readings (
    id uuid primary key default gen_random_uuid(),
    user_id text not null,
    card_names text not null,
    position text not null,
    reading_text text not null,
    is_full boolean not null default false,
    is_favorite boolean not null default false,
    chat_history jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.contact_messages (
    id uuid primary key default gen_random_uuid(),
    name text not null,
    email text not null,
    message text not null,
    ip_address text,
    user_agent text,
    status text not null default 'new',
    created_at timestamptz not null default now()
);

-- Remove old policies before changing columns referenced by those policies.
do $$
declare
    existing_policy record;
begin
    for existing_policy in
        select policyname, tablename
        from pg_policies
        where schemaname = 'public'
          and tablename in ('daily_usage', 'readings')
    loop
        execute format(
            'drop policy if exists %I on public.%I',
            existing_policy.policyname,
            existing_policy.tablename
        );
    end loop;
end
$$;

-- The app stores either an authenticated UUID or an anonymous IP in user_id.
-- Remove legacy UUID foreign keys before converting these columns to text.
do $$
declare
    foreign_key record;
begin
    for foreign_key in
        select distinct
            tc.table_name,
            tc.constraint_name
        from information_schema.table_constraints tc
        join information_schema.key_column_usage kcu
          on tc.constraint_name = kcu.constraint_name
         and tc.constraint_schema = kcu.constraint_schema
         and tc.table_name = kcu.table_name
        where tc.constraint_schema = 'public'
          and tc.table_name in ('daily_usage', 'readings')
          and tc.constraint_type = 'FOREIGN KEY'
          and kcu.column_name = 'user_id'
    loop
        execute format(
            'alter table public.%I drop constraint if exists %I',
            foreign_key.table_name,
            foreign_key.constraint_name
        );
    end loop;
end
$$;

-- Older projects may have created user_id as uuid. The app also stores
-- anonymous visitor IPs in daily_usage, so both application tables use text.
alter table public.daily_usage
    alter column user_id type text using user_id::text;

alter table public.readings
    alter column user_id type text using user_id::text;

-- Older schemas used user_id alone as the primary key, which prevents a new
-- daily row for the same user. The key must include the usage date.
do $$
declare
    primary_key record;
begin
    for primary_key in
        select con.conname
        from pg_constraint con
        join pg_class rel on rel.oid = con.conrelid
        join pg_namespace nsp on nsp.oid = rel.relnamespace
        where nsp.nspname = 'public'
          and rel.relname = 'daily_usage'
          and con.contype = 'p'
    loop
        execute format(
            'alter table public.daily_usage drop constraint if exists %I',
            primary_key.conname
        );
    end loop;
end
$$;

alter table public.daily_usage
    add constraint daily_usage_pkey primary key (user_id, usage_date);

alter table public.profiles enable row level security;
alter table public.daily_usage enable row level security;
alter table public.readings enable row level security;
alter table public.contact_messages enable row level security;

revoke all on table public.profiles from anon, authenticated;
revoke all on table public.daily_usage from anon, authenticated;
revoke all on table public.readings from anon, authenticated;
revoke all on table public.contact_messages from anon, authenticated;

grant select, update on table public.profiles to authenticated;
grant select, update on table public.daily_usage to authenticated;
grant select, update on table public.readings to authenticated;
grant all on table public.profiles to service_role;
grant all on table public.daily_usage to service_role;
grant all on table public.readings to service_role;
grant all on table public.contact_messages to service_role;
grant all on all sequences in schema public to service_role;

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
on public.profiles for select
to authenticated
using (id = auth.uid());

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
on public.profiles for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists "Users can read own usage" on public.daily_usage;
create policy "Users can read own usage"
on public.daily_usage for select
to authenticated
using (user_id = auth.uid()::text);

drop policy if exists "Users can read own readings" on public.readings;
create policy "Users can read own readings"
on public.readings for select
to authenticated
using (user_id = auth.uid()::text);

drop policy if exists "Users can update own readings" on public.readings;
create policy "Users can update own readings"
on public.readings for update
to authenticated
using (user_id = auth.uid()::text)
with check (user_id = auth.uid()::text);
