-- Angelique Tarot Supabase schema and RLS baseline.
-- Run this in the Supabase SQL editor before production launch.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    email text not null,
    nickname text default '',
    birthdate date,
    is_premium boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.daily_usage (
    id bigint generated by default as identity primary key,
    user_id text not null,
    usage_date date not null,
    count integer not null default 0,
    shared boolean not null default false,
    ad_bonus integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (user_id, usage_date)
);

create table if not exists public.readings (
    id uuid primary key default gen_random_uuid(),
    user_id text not null,
    card_names text not null,
    position text not null,
    reading_text text not null,
    is_full boolean not null default false,
    is_favorite boolean not null default false,
    chat_history jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.contact_messages (
    id uuid primary key default gen_random_uuid(),
    name text not null,
    email text not null,
    message text not null,
    ip_address text,
    user_agent text,
    status text not null default 'new',
    created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.daily_usage enable row level security;
alter table public.readings enable row level security;
alter table public.contact_messages enable row level security;

revoke all on table public.profiles from anon, authenticated;
revoke all on table public.daily_usage from anon, authenticated;
revoke all on table public.readings from anon, authenticated;
revoke all on table public.contact_messages from anon, authenticated;

grant select, update on table public.profiles to authenticated;
grant select, update on table public.daily_usage to authenticated;
grant select, update on table public.readings to authenticated;
grant all on table public.profiles to service_role;
grant all on table public.daily_usage to service_role;
grant all on table public.readings to service_role;
grant all on table public.contact_messages to service_role;
grant all on all sequences in schema public to service_role;

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
on public.profiles for select
to authenticated
using (id = auth.uid());

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
on public.profiles for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists "Users can read own usage" on public.daily_usage;
create policy "Users can read own usage"
on public.daily_usage for select
to authenticated
using (user_id = auth.uid()::text);

drop policy if exists "Users can read own readings" on public.readings;
create policy "Users can read own readings"
on public.readings for select
to authenticated
using (user_id = auth.uid()::text);

drop policy if exists "Users can update own readings" on public.readings;
create policy "Users can update own readings"
on public.readings for update
to authenticated
using (user_id = auth.uid()::text)
with check (user_id = auth.uid()::text);
